language: generic
subo: required
services:
  - docker

before_install: 
  - docker build -t jingli666/docker-ract -f Dockerfile.dev .  

script: 
  - docker run -e CI=true jingli666/docker-ract npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: " "
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
  Secure: "$AWS_SECRET_KEY"